# environment for running in AzureML
name: monai-azureml
channels:
  - pytorch
  - defaults
dependencies:
  - numpy>=1.20
  - pytorch>=1.9
  - torchvision
  - pip
  - python>=3.8
  - pip:
    - git+https://github.com/peterhessey/MONAI.git@6054-integrate-azureml-for-autorunner-training
    - hi-ml-azure>=0.2.19
