name: monai-azureml
channels:
  - defaults
dependencies:
  - pip
  - python>=3.8
  - pip:
    - git+https://github.com/peterhessey/MONAI.git@6054-integrate-azureml-for-autorunner-training
    - hi-ml-azure>=0.2.19
