name: monai
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - numpy>=1.20
  - pytorch>=1.8
  - torchvision
  - pytorch-cuda=11.6
  - pip
  - python>=3.8
  - pip:
    - -r requirements-dev.txt
