---
amp: true
bundle_root: null
ckpt_path: "$@bundle_root + '/model'"
data_file_base_dir: null
data_list_file_path: null
determ: false
fold: null
input_channels: null
learning_rate: 0.025
num_images_per_batch: 2
num_iterations: 40000
num_iterations_per_validation: 500
num_patches_per_image: 1
num_sw_batch_size: 2
output_classes: null
overlap_ratio: 0.625
patch_size:
- null
- null
- null
patch_size_valid:
- null
- null
- null
softmax: null
image_key: image
label_key: label
transform_train:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys:
    - "@image_key"
    - "@label_key"
  - _target_: EnsureChannelFirstd
    keys:
    - "@image_key"
    - "@label_key"
  - _target_: Orientationd
    keys:
    - "@image_key"
    - "@label_key"
    axcodes: RAS
  - _target_: Spacingd
    keys:
    - "@image_key"
    - "@label_key"
    pixdim:
    - 1
    - 1
    - 1
    mode:
    - bilinear
    - nearest
    align_corners:
    - true
    - true
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - INTENSITY_NORMALIZATION
  - _target_: CastToTyped
    keys:
    - "@image_key"
    - "@label_key"
    dtype:
    - "$np.float16"
    - "$np.uint8"
  - _target_: EnsureTyped
    keys:
    - "@image_key"
    - "@label_key"
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - _target_: SpatialPadd
    keys:
    - "@image_key"
    - "@label_key"
    spatial_size: "@patch_size"
    mode:
    - reflect
    - constant
  - _target_: RandCropByLabelClassesd
    keys:
    - "@image_key"
    - "@label_key"
    label_key: "@label_key"
    num_classes: "@output_classes"
    spatial_size: "@patch_size"
    num_samples: "@num_patches_per_image"
  - _target_: RandRotated
    keys:
    - "@image_key"
    - "@label_key"
    range_x: 0.3
    range_y: 0.3
    range_z: 0.3
    mode:
    - bilinear
    - nearest
    prob: 0.2
  - _target_: RandZoomd
    keys:
    - "@image_key"
    - "@label_key"
    min_zoom: 0.8
    max_zoom: 1.2
    mode:
    - trilinear
    - nearest
    align_corners:
    - null
    - null
    prob: 0.16
  - _target_: RandGaussianSmoothd
    keys: "@image_key"
    sigma_x:
    - 0.5
    - 1.15
    sigma_y:
    - 0.5
    - 1.15
    sigma_z:
    - 0.5
    - 1.15
    prob: 0.15
  - _target_: RandScaleIntensityd
    keys: "@image_key"
    factors: 0.3
    prob: 0.5
  - _target_: RandShiftIntensityd
    keys: "@image_key"
    offsets: 0.1
    prob: 0.5
  - _target_: RandGaussianNoised
    keys: "@image_key"
    std: 0.01
    prob: 0.15
  - _target_: RandFlipd
    keys:
    - "@image_key"
    - "@label_key"
    spatial_axis: 0
    prob: 0.5
  - _target_: RandFlipd
    keys:
    - "@image_key"
    - "@label_key"
    spatial_axis: 1
    prob: 0.5
  - _target_: RandFlipd
    keys:
    - "@image_key"
    - "@label_key"
    spatial_axis: 2
    prob: 0.5
  - _target_: CastToTyped
    keys:
    - "@image_key"
    - "@label_key"
    dtype:
    - "$torch.float32"
    - "$torch.uint8"
  - _target_: ToTensord
    keys:
    - "@image_key"
    - "@label_key"
transform_validation:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys:
    - "@image_key"
    - "@label_key"
  - _target_: EnsureChannelFirstd
    keys:
    - "@image_key"
    - "@label_key"
  - _target_: Orientationd
    keys:
    - "@image_key"
    - "@label_key"
    axcodes: RAS
  - _target_: Spacingd
    keys:
    - "@image_key"
    - "@label_key"
    pixdim:
    - 1
    - 1
    - 1
    mode:
    - bilinear
    - nearest
    align_corners:
    - true
    - true
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
  - INTENSITY_NORMALIZATION
  - _target_: CastToTyped
    keys:
    - "@image_key"
    - "@label_key"
    dtype:
    - "$np.float16"
    - "$np.uint8"
  - _target_: CastToTyped
    keys:
    - "@image_key"
    - "@label_key"
    dtype:
    - "$torch.float32"
    - "$torch.uint8"
  - _target_: ToTensord
    keys:
    - "@image_key"
    - "@label_key"
arch_ckpt_path: null
arch_ckpt: "$torch.load(@arch_ckpt_path, map_location=torch.device('cuda'))"
dints_space:
  _target_: monai.networks.nets.TopologyInstance
  channel_mul: 1
  num_blocks: 12
  num_depths: 4
  use_downsample: true
  arch_code:
  - "$@arch_ckpt['code_a']"
  - "$@arch_ckpt['code_c']"
  device: "$torch.device('cuda')"
network:
  _target_: monai.networks.nets.DiNTS
  dints_space: "@dints_space"
  in_channels: "@input_channels"
  num_classes: "@output_classes"
  use_downsample: true
  node_a: "$@arch_ckpt['node_a']"
