---
amp: true
bundle_root: null
ckpt_path: null
data_file_base_dir: null
data_list_file_path: null
determ: false
finetune:
  activate: false
  pretrained_ckpt_name: null
fold: 0
input_channels: null
learning_rate: 0.025
num_images_per_batch: 2
num_iterations: 400
num_iterations_per_validation: 50
num_patches_per_image: 1
num_sw_batch_size: 2
output_classes: null
overlap_ratio: 0.625
patch_size:
- null
- null
- null
patch_size_valid:
- null
- null
- null
softmax: null
loss:
  _target_: DiceFocalLoss
  include_background: true
  to_onehot_y: "$@softmax"
  softmax: "$@softmax"
  sigmoid: "$not @softmax"
  squared_pred: true
  batch: true
  smooth_nr: 1.0e-05
  smooth_dr: 1.0e-05
optimizer:
  _target_: torch.optim.SGD
  lr: "@learning_rate"
  momentum: 0.9
  weight_decay: 4.0e-05
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  optimizer: "$@optimizer"
  step_size: "$@num_iterations // 5"
  gamma: 0.5
validate:
  ckpt_name: null
  save_mask: true
  ouptut_path: null
infer:
  ckpt_name: null
  fast: false
  data_list_key: testing
  ouptut_path: "$@bundle_root + '/prediction_' + @infer#data_list_key"
