# manually trigger integration with the latest pytorch
name: integration

on:
  push:
    branches:
      - temp-test
  repository_dispatch:
    type: [integration-test-command]

jobs:
  setup-folders:
    container:
      image: nvcr.io/nvidia/pytorch:22.04-py3  # CUDA 11.6 py38
      options: --gpus "device=1" --ipc host  # shm-size 4g works fine
    runs-on: [self-hosted, linux, x64, command]
    steps:
    # checkout the pull request branch
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PR_MAINTAIN }}
        repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
        ref: ${{ github.event.client_payload.pull_request.head.ref }}
    - name: make updates
      run: touch hello.txt

  integration-auto3dseg:
    needs: setup-folders
    container:
      image: nvcr.io/nvidia/pytorch:22.04-py3  # CUDA 11.6 py38
      options: --gpus "device=1" --ipc host  # shm-size 4g works fine
    runs-on: [self-hosted, linux, x64, command]
    steps:
    - name: Install the dependencies
      run: |
        pwd && ls -a && git log -1 && which python

  integration-full-unit:
    needs: setup-folders
    container:
      image: nvcr.io/nvidia/pytorch:22.04-py3  # CUDA 11.6 py38
      options: --gpus "device=2" --ipc host  # shm-size 4g works fine
    runs-on: [self-hosted, linux, x64, command1]
    steps:
    - name: Install the dependencies
      run: |
        pwd && ls -a && git log -1 && which python
